### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by psychemedia** [AaronWatters/jp_proxy_widget#27]
Trying to install and use `jp_proxy_widget` in a MyBinder JupyterLab environment launched from the https://github.com/jupyter-widgets/jupyterlab-sidecar repo raises an *Error displaying widget: model not found* error message.

Running in a MyBinder environment launched from this (`jp_proxy_widget`) repo and the widget works fine.

Doing a `pip freeze`, the version numbers of Jupyter packages etc look the same across repos, so presumably they're using common Binder container layers.

Is the `jp_proxy_widget` package on PyPi complete? I've also tried installing the package from this repo into a not-this-repo Binder environment and the error still occurs?!

**Comment by AaronWatters** [comment]
I saw something like this with a lot of repositories, but I don't know about installing "on the fly" into a running lab instance.

The fix I came up with is to use something like this `postBuild` logic or some equivalent alternative.

https://github.com/AaronWatters/test_proxy_client/blob/main/postBuild

You need the latest version of nodejs and jupyterlab3 and to initialize the labextensions.

In other configurations I saw complaints about version numbers in the Javascript console.
Please see if that works for you.

**Comment by psychemedia** [comment]
Ah, thanks... `!jupyter labextension install jp_proxy_widget` did it...


In passing, I think there are simpler JupyerLab extension routes now (prebuilt federated extensions) but I've not really been tracking it or ever had much success at finding docs.

Related:

- [*Document how to build federated extensions for different JupyterLab distributions*](https://github.com/jupyterlab/jupyterlab/issues/9829)
- [*Improve the user experience and awareness about prebuilt extensions*](https://github.com/jupyterlab/jupyterlab/issues/10554)
